/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module display7seg_8 (
    input clk,
    input rst,
    output reg [6:0] seg,
    output reg [3:0] sel,
    input [1:0] dispmode,
    input [2:0] testvec
  );
  
  
  
  localparam MODE_RDY = 2'h0;
  
  localparam MODE_PASS = 2'h1;
  
  localparam MODE_FAIL = 2'h2;
  
  localparam MODE_RUN = 2'h3;
  
  localparam DISP_P = 7'h73;
  
  localparam DISP_A = 7'h77;
  
  localparam DISP_S = 7'h6d;
  
  localparam DISP_F = 7'h71;
  
  localparam DISP_I = 7'h30;
  
  localparam DISP_L = 7'h38;
  
  localparam DISP_R = 7'h50;
  
  localparam DISP_D = 7'h5e;
  
  localparam DISP_Y = 7'h6e;
  
  localparam DISP_T = 7'h78;
  
  reg [3:0] n;
  
  wire [7-1:0] M_sevenseg_seg;
  wire [4-1:0] M_sevenseg_sel;
  reg [28-1:0] M_sevenseg_digits;
  multi_seven_seg_11 sevenseg (
    .clk(clk),
    .rst(rst),
    .digits(M_sevenseg_digits),
    .seg(M_sevenseg_seg),
    .sel(M_sevenseg_sel)
  );
  
  wire [7-1:0] M_number_segs;
  reg [4-1:0] M_number_char;
  seven_seg_12 number (
    .char(M_number_char),
    .segs(M_number_segs)
  );
  
  always @* begin
    seg = M_sevenseg_seg;
    sel = M_sevenseg_sel;
    M_sevenseg_digits = 28'h0000000;
    n = {1'h0, testvec};
    M_number_char = n + 1'h1;
    
    case (dispmode)
      2'h0: begin
        M_sevenseg_digits = 28'h0142f6e;
      end
      2'h1: begin
        M_sevenseg_digits = 28'he7df6ed;
      end
      2'h2: begin
        M_sevenseg_digits = 28'he3dd838;
      end
      2'h3: begin
        M_sevenseg_digits = 28'hf000000;
        M_sevenseg_digits[0+6-:7] = M_number_segs;
      end
    endcase
  end
endmodule
