/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module addertester_4 (
    input clk,
    input rst,
    input trig,
    output reg [6:0] seg,
    output reg [3:0] sel,
    output reg [2:0] testvec,
    input [1:0] testresult
  );
  
  
  
  wire [7-1:0] M_disp_seg;
  wire [4-1:0] M_disp_sel;
  reg [2-1:0] M_disp_dispmode;
  reg [3-1:0] M_disp_testvec;
  display7seg_8 disp (
    .clk(clk),
    .rst(rst),
    .dispmode(M_disp_dispmode),
    .testvec(M_disp_testvec),
    .seg(M_disp_seg),
    .sel(M_disp_sel)
  );
  
  wire [3-1:0] M_test_testvect;
  wire [1-1:0] M_test_result;
  reg [3-1:0] M_test_teststep;
  reg [2-1:0] M_test_testresult;
  checker_9 test (
    .teststep(M_test_teststep),
    .testresult(M_test_testresult),
    .testvect(M_test_testvect),
    .result(M_test_result)
  );
  
  wire [2-1:0] M_ctrl_runstatus;
  wire [3-1:0] M_ctrl_testseq;
  reg [1-1:0] M_ctrl_trig;
  reg [1-1:0] M_ctrl_result;
  testctrl_10 ctrl (
    .clk(clk),
    .rst(rst),
    .trig(M_ctrl_trig),
    .result(M_ctrl_result),
    .runstatus(M_ctrl_runstatus),
    .testseq(M_ctrl_testseq)
  );
  
  always @* begin
    seg = M_disp_seg;
    sel = M_disp_sel;
    testvec = M_test_testvect;
    M_disp_dispmode = M_ctrl_runstatus;
    M_disp_testvec = M_ctrl_testseq;
    M_test_teststep = M_ctrl_testseq;
    M_test_testresult = testresult;
    M_ctrl_trig = trig;
    M_ctrl_result = M_test_result;
  end
endmodule
