/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module testtable_13 (
    input [2:0] in,
    output reg [2:0] out
  );
  
  
  
  localparam VECTABLE = 24'hfac688;
  
  always @* begin
    out = VECTABLE[(in)*3+2-:3];
  end
endmodule
